version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app/backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db  
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: my_database

  frontend:
    build: ./frontend
    ports:
      - "8003:8080"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  
      interval: 10s            
      timeout: 5s              
      retries: 5               
      start_period: 30s 

volumes:
  mysql_data: 